#APPLICATION BROWSER
browser = Chrome
#APPLICATION URL
Url = https://www.demoblaze.com/
#APPLICATION USERNAME AND PASSWORD
username = kamalisri.siva
password = kamali@1234
#Purchasedetails
name = kamalisri
country = india
city = chennai
creditcard = 352134
month = 6
year = 1998